DROP TABLE IF EXISTS TODOS;
DROP TABLE IF EXISTS TODO_CATEGORY;

CREATE TABLE TODO_CATEGORY (
    CATEGORY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE TODOS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    TODO_NAME VARCHAR(255) NOT NULL,

    TODO_DESCRIPTION VARCHAR(1000),

    STATUS VARCHAR(30) NOT NULL,

    PRIORITY VARCHAR(30) NOT NULL,

    TODO_TYPE VARCHAR(30) NOT NULL,

    DUE_DATE DATE NOT NULL,

    CREATION_DATE TIMESTAMP,

    LAST_UPDATED_DATE TIMESTAMP,

    CATEGORY_ID BIGINT,

    CONSTRAINT FK_CATEGORY
        FOREIGN KEY (CATEGORY_ID)
        REFERENCES TODO_CATEGORY(CATEGORY_ID)
);