name: Deploy Docker Image On Local
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker Image Tag"
        required: true
        default: "latest"
jobs:
  deploy:
    runs-on: self-hosted

    env:
      IMAGE_NAME: todo-application-prectice

    steps:
      - name: Login Docker Hub
        run:
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull Image
        run:
          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.image_tag }}

      - name: Stop Existing Container
        run: |
          docker stop spring-boot-app || true
          docker rm spring-boot-app || true

      - name: Run Container
        run:
          docker run -d --name todo-application-prectice -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.image_tag }}

      - name: Verify Container
        run: docker ps